### ISSUE TITLE
compare() does not work with tibbles

### ISSUE THREAD

**Issue by Si-Thu-Thein** [data-cleaning/validate#104]
Hello,

I have noticed that `compare()` (and also `confront()` ) does not work with tibbles but throws an error. I'm not sure if it is intended or not. Here is an example:
```
library(tidyverse)
data(retailers)
rules <- validator(turnover >=0, staff>=0, other.rev>=0)
# start with raw data
step0 <- retailers
# impute turnovers
step1 <- step0
step1$turnover[is.na(step1$turnover)] <- mean(step1$turnover,na.rm=TRUE)
# flip sign of negative revenues
step2 <- step1
step2$other.rev <- abs(step2$other.rev)
# create an overview of differences, comparing to the previous step
#this version works
compare(rules, raw = step0, imputed = step1, flipped = step2, how="sequential")
#this does not
compare(rules, raw = as_tibble(step0), imputed = as_tibble(step1), flipped = step2, how="sequential")
# Error: Can't subset with `[` using an object of class NULL.
# Call `rlang::last_error()` to see a backtrace
```

My current workaround is to convert tibbles to R dataframes by passing into `as.data.frame()` in the call.

**Comment by markvanderloo** [comment]
This is a problem with `tibble`. 

If you take a tibble, say `tbl`, and ask for its class, you get:

```
> class(tibble::tibble(x=1:3))
[1] "tbl_df"     "tbl"        "data.frame"
```

Note that the last entry is `data.frame`. This means that R thinks in many cases that a `tibble` is a data frame. Unfortunately the authors of `tibble` violate this assumption and adopted the bad practice of creating a subclass (tibble) of an existing class (data frame) and gave it different behavior for existing methods that is unexpected by base R. In particular it changes behavior of subsetting with `[`.

I personally find such choices unethical, considering the influence and popularity of the package -- this is [not the first time](https://github.com/markvanderloo/simputation/issues/17) I have to take time to explain this, and that is totally not your fault: I have the tidyverse developers to thank for that.

**Comment by markvanderloo** [comment]
And just make it absolutely clear: please do not hesitate to post any bug reports, questions or remarks: I am really grateful for the time you took to point out this confusion. I may add some notes to the documentation about tibbles. The workaround, by the way is simple: just call `as.data.frame` on a tibble and all works as expected.

**Comment by Si-Thu-Thein** [comment]
Hi Mark,
Thanks! I've posted this because I think other users may encounter this and may not know what to do. Considering the popularity of tidyverse, that's bound to happen. 
I've found the workaround `as.data.frame` just by chance and I think it would be good to have some notes about this tidyverse bug in the documentation.

**Comment by Si-Thu-Thein** [comment]
On a related note, it's also problematic when using reference datasets. If the reference dataset is tibble, variable selection by `dataset$variable` in yaml file got translated into `dataset[,"variable"]` in expression. But this expression does not return the variable but a single column tibble, and it's does not work as intended. The workaround is to use `dataset[["variable"]]` in yaml file rather than `dataset$variable`.

**Comment by markvanderloo** [comment]
ha, thanks for that last note!. We will document this before the next release.
