### ISSUE TITLE
field_length and check_field_length functions

### ISSUE THREAD

**Issue by luenhchang** [data-cleaning/validate#117]
Hi,
I am trying to replicate the code in 02-variable_level_checks.Rmd. While creating the following validation rules 
```
rules <- validator( nchar(as.character(size)) >= 2
                   ,field_length(id, n=5)
                   ,field_length(size, min=2, max=3)
                   )
```
I got 
Warning message:
Invalid syntax detected, the following expressions have been ignored:
[002] field_length(id, n = 5)
[003] field_length(size, min = 2, max = 3) 

Where can I access the field_length() and check_field_length()?

**Comment by markvanderloo** [comment]
Hi there,

thanks for your interest! The functions you mention are not in the current CRAN package, but only on github. We plan to release the next version in december.

If you want to try the development version, please have a look at the instructions in the `README.md`.

Cheers,
Mark
