### ISSUE TITLE
Check the uniqueness of a variable in groups while accounting for its missingness

### ISSUE THREAD

**Issue by luenhchang** [data-cleaning/validate#120]
Hi Mark,

I am wondering how I can write a validation rule in the `validate::validator()` function to check the uniqueness of a variable by groups while accounting for its missingness. Suppose my data have two columns- cohort and ID. I'd like to check these conditions and return the results:

1. Within cohorts, if a ID value has no duplicate, add 1 to the pass in the validation summary
2. Within cohorts, if a ID value has a duplicate, add 1 to the fail in the validation summary
3. Within cohorts, if there is a missing ID value, add 1 to the nNA in the validation summary

I have been able to evaluate the conditions using the dplyr package but I don't know how I can do something similar in your validator(). 

```
# Create some data
t <- data.frame( cohort=c(1,1,1,1,2,2,2,2,2)
                ,ID=c("A1","A2","A3",NA,"A1","A2","A2","A3",NA)
                ,stringsAsFactors = F)
t
#   cohort   ID
# 1      1   A1
# 2      1   A2
# 3      1   A3
# 4      1 <NA>
# 5      2   A1
# 6      2   A2
# 7      2   A2
# 8      2   A3
# 9      2 <NA>
```

to be checked whether the IDs are unique in cohorts

```
# Check uniqueness of ID in cohorts
t1 <- t %>% 
  group_by(cohort) %>% 
  mutate( ID_unique= !duplicated(ID)
         ,ID_unique_check= case_when( !is.na(ID) & ID_unique==TRUE ~ "pass"
                                     ,!is.na(ID) & ID_unique==FALSE ~ "fail"
                                     ,is.na(ID) ~ "nNA"))

t1
#   cohort ID    ID_unique ID_unique_check
#     <dbl> <chr> <lgl>     <chr>          
# 1      1 A1    TRUE      pass           
# 2      1 A2    TRUE      pass           
# 3      1 A3    TRUE      pass           
# 4      1 NA    TRUE      nNA            
# 5      2 A1    TRUE      pass           
# 6      2 A2    TRUE      pass           
# 7      2 A2    FALSE     fail           
# 8      2 A3    TRUE      pass           
# 9      2 NA    TRUE      nNA            
```

Any thoughts?

Chang

**Comment by markvanderloo** [comment]
Hi Chang,

The new version (1.0.0) of validate that is planned for release this week will have a `by` argument in the `is_unique` function. This will allow you to do group-wise tests for uniqueness.

The question on `NA` is more subtle. For example, given the following data with two records.
```
X1 X2
1  2  
1 NA
```
In principle we can not now whether the second record is duplicated, so an `NA` result seems in order. However, this
implies that we also cannot know whether the first record is duplicated. So having missing values in key(s) in any record
affects the outcome of other, similar records.

It is therefore probably better to use `is_complete` separately to test for completeness. Or you can create a rule checking both:
```{r}
is_unique(X1, X2) & is_complete(X1, X2)
```
