### ISSUE TITLE
R STUDIO HELP

### ISSUE THREAD

**Issue by georgiazoller** [data-cleaning/validate#121]
model.1 -> lm(POLICEW4_5 ~ F_SEX_FINAL + F_AGECAT_FINAL + F_ATTEND_FINAL, data=POLICE)

Summary(model.1)

this is my code.

This is the error i get: Error in h(simpleError(msg, call)) :

error in evaluating the argument 'x' in selecting a method for function 'Summary': object 'model.1' not found

**Comment by markvanderloo** [comment]
Hello Georgia,  you are using `->` and not `<-` to assign to `model.1`.

Having said that, this is not the forum to ask such questions. Your question is a general R question, you can ask such questions at the [R-help](https://www.r-project.org/mail.html) mailing list, or at [stackoverflow.com](https://stackoverflow.com/). For R Studio questions, you can ask help from the [rstudio community](https://community.rstudio.com/).

The current location is for questions and bug reports about the [validate](https://cran.r-project.org/package=validate) R package.
