### ISSUE TITLE
plot() displaying incorrect names beside each rule, unlike barplot()

### ISSUE THREAD

**Issue by jkennedyie** [data-cleaning/validate#123]
Nice package. I have a confront result. When I pass to barplot() it displays correct rule name to the left of each rule. When I pass same result to plot() it displays incorrect rule names.

Will attempt to create a MWE but this might help:

Confront Results:
![image](https://user-images.githubusercontent.com/1921660/103243414-b2732000-4951-11eb-8f63-6a97d18040cc.png)

Correct barplot():
![image](https://user-images.githubusercontent.com/1921660/103243432-c1f26900-4951-11eb-967d-a516756d8976.png)

Incorrect plot() - V1 and V2 are not the correct rule names:
![image](https://user-images.githubusercontent.com/1921660/103243461-d46ca280-4951-11eb-8e26-321cc941214c.png)

**Comment by jkennedyie** [comment]
Minimum Working Example:
```
library(validate)
rules <- validator(field_length(speed, min = 1)
                 , speed >= 0
                 , dist >= 0
                 , speed/dist <= 1.5
                 , cor(speed, dist)>=0.2)

out <- confront(cars, rules)

# The fails are on rule V4:
summary(out)

# Correctly labelled V4 here:
barplot(out)

# Incorrectly labelled V3 here:
plot(out)
```

**Comment by jkennedyie** [comment]
Ah. I now realise that field_length() errors if min is specified and max is not.
If max parameter is added then field_length() does not error and plot() works as expected.

I suggest 
 * refining field_length() so that it can handle when only min is specified
 * refining plot() so that it can handle situations when an Error has occurred in a validation rule

Thank you for sharing this package. Very useful.

**Comment by markvanderloo** [comment]
Thanks for taking time to  (re)post and for your suggestions John! Will take into account for the next release.
