### ISSUE TITLE
Error  -Not all rules have record-wise output. Can I filter for record-wise output only in the confront object

### ISSUE THREAD

**Issue by jcvall-olympus** [data-cleaning/validate#127]
I am trying to use the violating function to ultimately generate a dataframe of all record exceptions, to then pass it on to a csv file.  I have both record-wise and aggregate validator objects and I receive an error when I use violating function.

Can I filter for record-wise output only in the confront object to then pass to a dataframe?  My goal is to have a dataframe where the rules are violated for the record-wise exceptions.

**Comment by mutahiwachira** [comment]
Looking at the source code it seems like all rules must have record-wise output in order for it to work. So yes, based on my understanding you would have to first have to filter out the aggregate rules/confrontations before passing to `violating`.

**Comment by markvanderloo** [comment]
There is no way to filter on the dimension structure of the output. But, if you know for example that rules 1-10 are record-wise rules and rules 11-15 aren't you can subset your confrontation object with `[]`:

See the last part of [Section 7.7](https://data-cleaning.github.io/validate/sect-work.html#confrontation-objects). in the cookbook.

**Comment by jcvall-olympus** [comment]
Thank you.  Love the package. Cannot thank you enough.  I think I will just create two txt files one for record-wise rules and the other global rules txt. Thanks for both of your responses.
