### ISSUE TITLE
Advice for validating when multiple data.frames are required (via a join for example)

### ISSUE THREAD

**Issue by kieran-mace** [data-cleaning/validate#130]
I'm looking for advice on the correct way to validate data when one must do a join between two tables.

``` r
library(tidyverse)
library(validate)

# check that each band member has at least one instrument
band_members %>% 
  left_join(band_instruments, by = "name") %>%
  group_by(name) %>% 
  summarise(num_instruments = n_distinct(plays, na.rm = TRUE)) %>%
  check_that(num_instruments > 0)
#> `summarise()` ungrouping output (override with `.groups` argument)
#> Object of class 'validation'
#> Call:
#>     check_that(., num_instruments > 0)
#> 
#> Confrontations: 1
#> With fails    : 1
#> Warnings      : 0
#> Errors        : 0
```

Should I consider making indicators after the join? Would the error be assigned to the left, or right table? 

<sup>Created on 2021-02-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by markvanderloo** [comment]
Hi there,

The `join` statements have no influence on `check_that()`, other than that you change which columns are present.

The output of `check_that()` is a `validation` object that holds information on the results of the checks, and some metadata (e.g. could the check be performed?). You can get a summary of the output by appending `%>% summary()`  after `check_that()`, or you can turn the results into a data.frame by appending `%>% as.data.frame()`


If you want to select only the valid records, you can do something like this:

```r
df <- band_members %>% 
  left_join(band_instruments, by = "name") %>%
  group_by(name) %>% 
  summarise(num_instruments = n_distinct(plays, na.rm = TRUE)) %>%
  satisfying(validator(num_instruments > 0))
```

**Comment by kieran-mace** [comment]
Sorry I think my example may have confused issues. 

It seems to me that the paradigm available is:

1 data.frame + rules → confront → results 

so if I need to do a join I would:

data.frame.a + data.frame.b → merge/join → data.frame.c + rules → confront → results

Which means my results are on the rows of c, not a or b. 

If I want to validate a, or b, it's unclear how I would attribute an error to either table.

**Comment by markvanderloo** [comment]
This will require data manipulation. It depends a bit on data circumstances and what  you want to do, but what you describe is correct. 

The following may help you.

If the (joined) input data frame has a variable that has a primary key or set of variables that together form a primary key, then you can use the `key=` argument in `confront()`. If you reshape the result of `confront()` into a data frame using `as.data.frame`, the key(s) will be there. You can use that to merge the results with data frame a or b, in your example.
