### ISSUE TITLE
How to solve Error in (function (classes, fdef, mtable)  :   unable to find an inherited method for function ‘assays’ for signature ‘"list"’

### ISSUE THREAD

**Issue by yyyyy20000** [data-cleaning/validate#139]
I want to use assays function of SummarizedExperiment, but I have encountered the error as below:
`assays(liver)$coutns
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘assays’ for signature ‘"list"’
`
I can't find any solutions on the Internet. Does anyone know how to solve it?

**Comment by markvanderloo** [comment]
Sorry, I do not see how thei question is related to the validate R package. Please post this question on another forum.
