### ISSUE TITLE
different naming of rules when reading from csv,yml and hardcoded

### ISSUE THREAD

**Issue by Wytzepakito** [data-cleaning/validate#148]
If rules are read from a  dataframe which was made by reading a csv and this dataframe contains empty cells for the name of rules then these rules will not contain a name in the validator object. 

However if the exact same ruleset is written in yaml and again the rules do not contain a name( no name field or name field with empty string) then the rules get an autogenerated name which is the letter 'V' followed by the index of the rule.

The latter also applies when hardcoding the ruleset without writing them in a data frame

I find this difference a bit odd.

Otherwise I am very happy with the Validate package!

**Comment by markvanderloo** [comment]
Hi Wytze, thanks for noting this. That's a bug.
