### ISSUE TITLE
Make 'validate' pipe-ready

### ISSUE THREAD

**Issue by markvanderloo** [data-cleaning/validate#15]
The ```%>%``` and ```%T%``` operators of the magrittr package are realy interesting for validating data flows.

**Comment by markvanderloo** [comment]
Another option would be to have a user-friendly ```check_that``` function built upon validate's infrastructure, e.g.

```
iris %>% check_that(Sepal.Width < 5*median(Sepal.Width), Petal.Length > 0)
```

**Comment by edwindj** [comment]
That sounds very similar (if not identical) to [`ensurer::ensure_that`](http://cran.r-project.org/web/packages/ensurer/vignettes/ensurer.html)
