### ISSUE TITLE
Efficiently generating df per rule using violating()

### ISSUE THREAD

**Issue by bzlato** [data-cleaning/validate#150]
Hello. 
I like the violating functionality but when communicating with others on the data issues encountered, it's useful to split up the "errors" rule by rule, even if there are some rows that might be failing multiple rules.

Since we strongly prefer tidyverse in the company I thought I could use map() to look through
violating(df, out[1]), violating(df, out[2]) but map() doesn't think "out" is a list and I haven't figured out a way to apply it.

Best I can do so far with a loop is:

list <- list()
for (i in 1:16) {
  temp <- violating(df, out[i])
  list[[i]] <- temp
}
iwalk(list, ~write.csv(.x, file = paste0("question", .y, ".csv")))

Is there a better way to use violating() or map() with it? 

Thank you.

**Comment by markvanderloo** [comment]
I'm not near a computer right now, but have you tried `lapply`? Not tidyverse but I don't think it forces a list input.
