### ISSUE TITLE
Error in section 3.3 of Cookbook

### ISSUE THREAD

**Issue by rmsharp** [data-cleaning/validate#163]
Text at end of section 3.3 says "blocks containing GDP and Export have entire records missing" where as all records (1199) failed and blocks containing ## [1] "gdp"     "import"  "export"  "balance" have entire records missing. 

I did not find anything wrong with the definition of the keyset but the results indicate something has changed since the text was written. 

It seems at least one additional unit test will be needed.

**Comment by markvanderloo** [comment]
Thanks. I now see something strange in de the code. I use `all_keys` instead of `keyset` in the example. Will fix.

**Comment by markvanderloo** [comment]
Thanks, there was a spelling error in one of the keys. Fixed in the online version of the cookbook.
