### ISSUE TITLE
Minor typos on the cookbook

### ISSUE THREAD

**Issue by PedroNSilva** [data-cleaning/validate#167]
Thanks for the excellent material. 
I have found a couple of minor typos on the cookbook.
In section 1.1, the text
"Summarizing, the basic workflow in validate is to create a rule set, confront a data set with the rules in the rule set, and than analyze or use the results further."
I believe you meant to say as below (the word to change is CAPITALISED)
"Summarizing, the basic workflow in validate is to create a rule set, confront a data set with the rules in the rule set, and THEN analyze or use the results further."

In section 2.6, the text
"By default, in_range includes the boundaries of the range, so the above rule is equivalent to incl.prob >= 0 and incl.prob <= 0."
should read
"By default, in_range includes the boundaries of the range, so the above rule is equivalent to incl.prob >= 0 and incl.prob <= 1."

The last value should be the upper limit of the range.

Again, thanks for the excellent material and the package, which is very helpful.

Pedro

**Comment by markvanderloo** [comment]
Thanks for noting Pedro! Updated in development version.

**Comment by PedroNSilva** [comment]
You're most welcome, Mark.

Thanks for the feedback. Kind regards, Pedro

Pedro Luis do Nascimento Silva
IBGE - Escola Nacional de Ciências Estatísticas - National School of
Statistical Sciences
SCIENCE - Sociedade para o Desenvolvimento da Pesquisa Científica -
Secretário
Phone: +55 21 994633376


Em seg., 11 de jul. de 2022 às 05:07, Mark van der Loo <
***@***.***> escreveu:
