### ISSUE TITLE
Test new data against existing data

### ISSUE THREAD

**Issue by kleinerChemiker** [data-cleaning/validate#171]
I am looking for the posibility to test new data against existing data before it is joined to the existing data.

E.g. anually new data is added. Some of the tests may be:
- are there new values (e.g. IDs) or are some values missing
- are there new combinations of values or combination of values missing
- are nummeric values within one order of magnitude around the median of the existing values
- are nummeric values within x times the standard deviation
- tests not relating to existing data, e.g. if a value is within a certain range 

tia
MIK

**Comment by markvanderloo** [comment]
You may be interested in the `validatesuggest` package by @edwindj
