### ISSUE TITLE
Cookbook: table of contents doesn't work?

### ISSUE THREAD

**Issue by etiennebacher** [data-cleaning/validate#172]
Hello, it seems that the links to sections and subsections in the cookbook are broken. When I hover "1. Introduction to validate", it shows me the address "sect:intro.html". Clicking on it doesn't do anything and opening it in a new tab makes "Page not found".

I tested with Firefox 112 and Chrome 111 (on Windows)

Thanks a lot for this package!

**Comment by DavZim** [comment]
FWIW, you can open the content in the vignette form, which has the identical but working content: https://cran.r-project.org/web/packages/validate/vignettes/cookbook.html

**Comment by etiennebacher** [comment]
Oh nice, thank you!

**Comment by markvanderloo** [comment]
Cause: Something changed in how bookdown (or one of the 36 pkgs it recursively depends on) works, causing references to labels with a colon in them to fail. I used to have labels like `{#sect:intro}`, these and references to those labels are now replaced by `{#sect-intro}`.
