### ISSUE TITLE
Alternative naming of "calls"?

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/validate#28]
Perhaps we should relabel "calls", because it is a internal R feature, namely a R expression that is "callable" (can be evaluated).  It will likely be unknown to users what "calls" are or mean.

Alternatives:
- "expr"  
- "expression"
- "rule"

**Comment by markvanderloo** [comment]
expr is probably the best, as this is what is used in the yaml format

**Comment by edwindj** [comment]
Agree! It is also nice to be consistent...

**Comment by markvanderloo** [comment]
I'll do it next week. This will probably also flush out a couple of hacks
where the slot is accessed in stead of using the getter function :).
