### ISSUE TITLE
A miss slot for rule objects

### ISSUE THREAD

**Issue by markvanderloo** [data-cleaning/validate#29]
A `miss` slot could take values `NA` (default), `TRUE` or `FALSE` and represents the value to return when a rule yields a missing value.

**Comment by kykuo** [comment]
Will this be implemented?

**Comment by markvanderloo** [comment]
Eventually, yes. If you use the `v <- validator(...); confront(dat, v)` consturction you can set a general option like so for example

```r
# replace result of validating statements returning NA with FALSE
confront(dat, v, na.value=FALSE)
```

See also `?voptions` or type `voptions()` at the command line.

**Comment by kykuo** [comment]
@markvanderloo Is there a way to specify this at the validator level?

The use case I'm considering is that we may expect NAs from some columns and not others. But perhaps it's cleaner to add e.g. `& !is.na(my_var)` to the condition. What would be the idiomatic way to incorporate this?

**Comment by markvanderloo** [comment]
I think that's probably a good idea :+1:
