### ISSUE TITLE
Tolerances on (linear) equalities

### ISSUE THREAD

**Issue by markvanderloo** [data-cleaning/validate#47]
We need to think about the following case. Given the rule

```
x == y
```
We can incorporate some roundoff errro by transforming to

```
abs(x-y) < eps
```
with some chosen constant `eps=lin.eq.eps` (or `num.eq.eps`). Alternatively we can also translate the `abs` function and create the equivalent
```
-(x-y) < eps
x-y < eps
```

**Comment by markvanderloo** [comment]
Writing spurs thought :).

I guess within `validate`, for the purpose of confrontation we can do the former: translate to `abs(x-y) < eps`. Within `validate.errloc` we can do the second.

**Comment by edwindj** [comment]
Agreed! Some parts to rewrite equality expressions into inequalities are present in validate.errloc

**Comment by edwindj** [comment]
Another option could be to rewrite it into an `all.equal` statement which is arguably the most natural R thing to do

**Comment by markvanderloo** [comment]
I tried that :-) since it would work for nonnumerics as well, but `all.equal` expects two vectors of equal size. That would make translation rather awkward.

**Comment by markvanderloo** [comment]
I now added the option `lin.eq.eps` which, if non-zero, only causes linear rules to be translated to the `abs`-version. Since it is difficult to discover whether variables (or outcomes of R-statements) are numeric, and also since linear statements are very common I think this is a good compromise for now. Users can always do
```
some_nonlinear_complex_function_of(x) < their_own_epsilon
```
to formulate rules in the non-linear case., See upcoming push

**Comment by markvanderloo** [comment]
btw: the slack introduced in `validate.errloc` could be set to 
```
max(lin.eq.eps, [the default for errloc])
```
but we'll have to see how user-friendly that is. I put the default for `lin.eq.eps` to 0 so users must explicitly set a tolerance. Not sure about that choice really. In the future we could possibly do this rule-wise as well.

**Comment by markvanderloo** [comment]
ok. Changing the default to 1e-8. Since this will not hurt comparisons between integer-rounded values, and works better in many cases of fractional numbers it is probably better. It is also reported in the summary of a confrontation object (since the actually evaluated expression is shown).

**Comment by markvanderloo** [comment]
for general equality rules we could also write our own `eq` function that can handle numeric and categorical data and takes a tolerance.
