### ISSUE TITLE
functional dependency operator

### ISSUE THREAD

**Issue by markvanderloo** [data-cleaning/validate#49]
We need a decision on this. We currently have implemented the `~` and the `%->%` synonym.

I finally decided I like the  `%->%` better. However, it has precedence over `+`, so the statement
```
A + B %->% C
```
is interpreted (parsed) as
```
A + (B %->% C)
```
while
```
A + B ~ C
```
parses to
```
(A + B) ~ C
```
Here's the precedence list from the [R lang def](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Infix-and-prefix-operators)
```
::
$ @
^
- +                (unary)
:
%xyz%
* /
+ -                (binary)
> >= < <= == !=
!
& &&
| ||
~                  (unary and binary)
-> ->>
=                  (as assignment)
```

Since we need a) a relational operator and b) a combination operator. I now vote that we use the `~` again...

**Comment by edwindj** [comment]
(incidently online) agreeing with you on all accounts...
Op 17 aug. 2015 14:15 schreef "Mark van der Loo" <notifications@github.com>:
