### ISSUE TITLE
Add `.` to allowed syntax

### ISSUE THREAD

**Issue by edwindj** [data-cleaning/validate#50]
It would make `validate` more expressive if we allowed self referencing in the statements, meaning that the data set to be checked can be used in the syntax statements.

A good candidate is `.` since this is also used by `magrittr` and `dplyr`:

e.g.
```
v <- validator(
   rich := subset(., income_class == "rich"),
   mean(rich$income) >= 1e6 
)
```

Implementation would be simple: just add `.` to the environment in which the confrontation takes part.

**Comment by markvanderloo** [comment]
done in 0.1.5
