### ISSUE TITLE
fail and stop execution

### ISSUE THREAD

**Issue by elikesprogramming** [data-cleaning/validate#54]
It would be nice that validate optionally let you stop the execution when a confrontation fails. Something similar to the function `ensure_that()` in the `ensurer` package (I was using it before, but `validate` has a much cleaner and convenient syntax/approach).

**Comment by markvanderloo** [comment]
It is actually possible. From the vignette (note the spelling error in `height`):

```
  v <- validator(hite > 0, weight>0)
  confront(women, v, raise='all')
```

By default, errors are 'caught', meaning they don't stop execution. Using raise='all' causes errors to be raised. This is especially useful for debugging rules.

This doesn't work for `check_that`, by the way.

**Comment by elikesprogramming** [comment]
thanks, but yeah, I was not explicit enough. I meant that it would be nice that `check_that` would raise errors. What I actually like of `validate` over `ensurer` or `assertive` is the clean syntax and simplicity of `check_that`. I am not much interested in reusable validators and so on. Just a convenient way to validate conditions on the go, so that the code fails early if something is different than expected and avoid error propagation that could be difficult to debug later. But for that, what I like is the simplest/cleanest way, so that validation does not interfere/obscure the other code and that the validation itself is not not error prone.

**Comment by markvanderloo** [comment]
Aha, you can set the general option:

```
validate_options(raise="all")
```

**Comment by simonthelwall** [comment]
Would it be possible to describe this behaviour in the introduction vignette? I've read the vignette but didn't realise this was possible.

**Comment by markvanderloo** [comment]
Sure, we'll try to fit that into the next version
