### ISSUE TITLE
allow validation of data.frames of class tbl_df

### ISSUE THREAD

**Issue by dusko** [data-cleaning/validate#55]
Packages like `readr` or `dplyr` may add additional class `tbl_df` into `data.frame` object.
Function `check_that` fails for these kinds of DF.

```r
library(validate)
packageVersion("validate")
class(women)
women <- dplyr::tbl_df(women)
class(women)
cf <- check_that(women, height > 0, weight > 0, height/weight > 0.5)
summary(cf)
```

Result into:

```r
> library(validate)
> packageVersion("validate")
[1] ‘0.1.3’
> class(women)
[1] "data.frame"
> women <- dplyr::tbl_df(women)
> class(women)
[1] "tbl_df"     "tbl"        "data.frame"
> cf <- check_that(women, height > 0, weight > 0, height/weight > 0.5)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘confront’ for signature ‘"tbl_df", "validator", "missing"’
> summary(cf)
Error in summary(cf) : object 'cf' not found
```

**Comment by markvanderloo** [comment]
Indeed.

We don't have support for tbl, (which I believe is nowadays called a tibble), `data.table` and so on yet, but we aim to support this in the future. In fact, we work with S4 methods so we have multiple inheritance, allowing for extentions to different subclasses of both data objects and validator objects.

**Comment by edwindj** [comment]
It works when library "methods" is called (because all these classes are subclasses of `data.frame`)

Currenty easy fix is to use: `library(methods)`, and the general fix is to add an `import(methods)` to `validate`

**Comment by edwindj** [comment]
(`tbl` is a subclass of `data.frame`)

**Comment by markvanderloo** [comment]
True, but I think it won't work with tbls that represent interfaces to a data base since we do not use any dplyr function under the hood that catches such differences.

`validate` actually imports 'methods', but this does not make the package visible globally. I think we can document this in the vignette.

**Comment by edwindj** [comment]
You're right that we don't use the `dplyr` interfaces yet. 
However we could do an `as.data.frame` internally: this would transform a `tbl` to `data.frame`. (seems at the moment better than a cryptic error). 
Alternative would be to implement `tbl_sql` with an error: "please convert the data to an `data.frame` (or somehting similar).

**Comment by markvanderloo** [comment]
We'll put it on the list for 0.2 :-)

**Comment by dusko** [comment]
Mark & Edwin. Thank you ;-)
