### ISSUE TITLE
implement expected failures

### ISSUE THREAD

**Issue by RoyalTS** [data-cleaning/validate#58]
pytest has the ability to specify expected failures, i.e. known exceptions to the rule that should be reported as failures but as non-catastrophic failures (http://pytest.org/latest/skipping.html). Could something similar be implemented for validate?

**Comment by markvanderloo** [comment]
I'm not familiar with pytest, but from a quick glance at the documentation it seems to be a package for software testing, whereas 'validate' is aimed at checking properties of (meta)data. So I am not sure what you mean with expected failure in the context of validate. Could you give a small example?
