### ISSUE TITLE
Better error localisation capabilities

### ISSUE THREAD

**Issue by markvanderloo** [data-cleaning/validate#61]
It would be useful for users to receive a better indication of where the error is located. Currently, when one applies a rule to a dataset, one obtains a vector whose length is equal to the "passes" that were performed. It would be useful if each pass could be linked to some record/dataset identifier, in order to make localisation easier. I recognise that it may not be trivial to do this algorithmically for all cases, since the number of passes and the nature of the needed identifiers depends on the rule itself. One option could be to give the user the possibility to define for each rule, as an extra metadata element, which fields should be used to assist users in localising the error in the dataset. [suggested by Luca Gramaglia]

**Comment by sfinnie** [comment]
I'm struggling with this atm.  In order for the data owner to fix identified errors, I need to aggregate failure messages back to the offending items (cells).  Something like:

        ( [1,4], ("must be > 0", "must be unique"),
          [8,6], ("must be unique"),
          [126,6], ("must be unique"))

It's not obvious how to do the mapping.  Ultimately, I'd like to write these back out to a revised .xlsx file, where errors are highlighted against offending cells (e.g. as cell comments).  Our data owners are administrators, not R users.  I can't tell them what the answer is; but need to make it easy to locate & fix erroneous values.

Willing to contribute to a solution if you have any suggestions on how to do it. Thanks.

**Comment by ogroendal** [comment]
We also have this issue in our organization. We have a data archive system where we solve it by having meta data on what variable to assign the error to. It would be great if validate supported something similar, making it easier to map validate to our internal system.

**Comment by markvanderloo** [comment]
@sfinnie we are working on a standardized validation report which will support such functionality. Should be finilalized in the summer. It is not trivial, by the way.

you may also want to have a look at the [errorlocate](https://cran.r-project.org/web/packages/errorlocate/index.html) package, which does record-wise error localization.

**Comment by markvanderloo** [comment]
I'm going to close this issue. The as.data.frame method for `confrontation` objects go a long way of solving this. Try e.g. (with the dev. version you can get from our `drat` repo).
```r
v <- validator(height > 0, sd(weight)>0)

women$id <- letters[1:15]
(out_v <- confront(women,v,key="id"))

as.data.frame(out_v)
```
