### ISSUE TITLE
Bug in created() assignment ?

### ISSUE THREAD

**Issue by AndrewRGibson** [data-cleaning/validate#65]
Very impressed with your package but think I have found a minor bug when trying to assign to a validator's "created" values (code below).  Hope this helps.

v <- validator(weight<150, Fred < Jim) 
created(v) <- rep(as.POSIXct('2015-01-01'),length(v))
_Error in checkAtAssignment("rule", "description", c("POSIXct", "POSIXt" : 
  c("assignment of an object of class “POSIXct” is not valid for @‘description’ in an object of class “rule”; is(value, \"character\") is not TRUE", "assignment of an object of class “POSIXt” is not valid for @‘description’ in an object of class “rule”; is(value, \"character\") is not TRUE")_
>

**Comment by markvanderloo** [comment]
Confirmed, and solved now. Thanks for reporting!

The drat version (see README at the main page) contains the fix.
