### ISSUE TITLE
validator creation from rules in character vectors

### ISSUE THREAD

**Issue by AndrewRGibson** [data-cleaning/validate#66]
I can see how to work round this with what's there but it may be useful to allow validator defintion from rules defined in a character vector.  My thinking is that I may want to store rule definitions in a database, retrieve them to a dataframe and just pass in the character vectors for rules, names, labels, descriptions etc.  to one function.

**Comment by markvanderloo** [comment]
this can now be done (>-0.2, check the current `drat` version) by reading rules from a data.frame, e.g.

```r
d <- data.frame(rule=c("x>0","y>0"))
validator(.data=d)
```
