### ISSUE TITLE
Using ifelse in validation

### ISSUE THREAD

**Issue by kevinykuo** [data-cleaning/validate#68]
Is this supposed to work?

```
df <- data.frame(A = c("X", "Y"), B = c("Y", "Y"))

df %>%
  check_that(ifelse(A == "X", B == "X", B == "Y")) %>% 
  summary
# [1] error   warning
# <0 rows> (or 0-length row.names)
# Warning message:
#   In ini_validator(.self, ..., .file = .file) :
#   Invalid syntax detected, the following expressions have been ignored:
#   [001] ifelse(A == "X", B == "X", B == "Y")
```

**Comment by markvanderloo** [comment]
`ifelse` is not a 'validating statement': it does not return a logical. We should include more examples in the vignettes, but you can use `if()...` for conditional rules, and `validate` will vectorize it for you. Note that these are interpreted as a _logical implementation_. So

if ( P )  Q

Where P and Q are validating statements, is interpreted as  

(NOT P) OR Q

So the `if` is not to be used for selecting subsets for which a rule is to be executed: it is executed for all records (but the effect is more or less similar). 

My [slides](http://www.slideshare.net/MarkVanDerLoo/data-validation-infrastructure-the-validate-package) from useR2016 contain a bunch of examples (and a sharper definition of 'validation').

**Comment by kykuo** [comment]
If I want to write "if (P) Q else R" should I be writing `(!P & R) | (P & Q)`?

Seems like validate isn't interpreting the "else R" part, i.e. when I look at "expression" in the confrontation summary I only see `!P | Q`.

**Comment by markvanderloo** [comment]
if-then-else is now supported. Note that it follows the following formal replacement:

```
     IF P THEN Q ELSE R 
<=>  (IF P THEN Q) AND (IF NOT(P) THEN R)
<=>  (NOT(P) OR Q) AND (NOT(NOT(P)) OR R)
<=>  (NOT(P) OR Q) AND (P OR R)
```
