### ISSUE TITLE
growing validate objects

### ISSUE THREAD

**Issue by RMHogervorst** [data-cleaning/validate#71]
request: a way to grow validator objects. 
Usecase: 

While I'm interactively going through a script I would like to add rules to the same validator object.

```
v <- validator(weight > 0) 

v <- v + validator(height > 0)

v
## Object of class 'validator' with 2 elements:
##  V1: height > 0
##  V2: weight > 0
```

**Comment by markvanderloo** [comment]
Good point. This is on our todolist as well. Only difficulty is how to handle options attached to both objects.

**Comment by RMHogervorst** [comment]
yes that could conflict of course

**Comment by GuiMarthe** [comment]
Wouldn't it be a matter of the programmers choice? I mean, maybe he would like to check for something twice. And if it is programmers choice to  check for more restrictive characteristics (such as validate(x > 3) + validate(x > 5))  wouldnt it be a matter of creating two bool series and && them?

**Comment by markvanderloo** [comment]
Well, if you create a list of  validating statements (which is what a `validator` object in essence is) this already implies you'd like both rules to be satisfied. IN any case, there are good reasons to not want something redundant like x > 3 in there if x > 5 is already present. Especially if you're going to do error localisation later on.

In any case, the issue at hand here is not adding rules, but how to handle options. A validator object can also store local options, such as what to do in case of a missing value. If these options differ per object, the question is what to do then. At the moment we cannot set options per rule.

**Comment by markvanderloo** [comment]
implemented. Addition creates a new object with default (global) options.
