### ISSUE TITLE
dplyr in yaml expr

### ISSUE THREAD

**Issue by RoyalTS** [data-cleaning/validate#72]
Perhaps I'm just going about this the wrong way, but how would I use a `dplyr` "pipeline" in a yaml `expr`? Here's an example in which I want to make sure that each group has exactly 48 members:

    group_by(grouping) %>% 
      count %>%
      filter(n!=48) %>% nrow == 0

(not the most elegant solution, I'll admit, but it'll do as an example)

**Comment by markvanderloo** [comment]
Why not use

all(table(grouping)) == 48

Nothing wrong with good old base R ;-)

**Comment by markvanderloo** [comment]
Sorry, should be

```r
all(table(grouping)==48)
```

**Comment by RoyalTS** [comment]
I get that this solves this particular issue. But there's loads and loads of situations where I want to perform tests on the results of more complex manipulations and for these dplyr is my weapon of choice these days. And so it'd be nice to be able to use that weapon within validate.

**Comment by markvanderloo** [comment]
I'm not b testing this as I'm writing from my mobile phone, but the dot (.) Refers to the whole days set so:

```r
group_by_(., "grouping")
```

Should probably work, maybe.

Also, using free text format is probably easier in this case. I often define rules in free text, read, export to yaml and then define other fields.

Bit quirky, in the future we want to add roxygen-like support.
