### ISSUE TITLE
Data frames with an additional class attribute are not supported

### ISSUE THREAD

**Issue by paulponcet** [data-cleaning/validate#73]
The following generates an error: 

    class(women) <- c("my_data.frame", "data.frame")
    check_that(women, height > 0)

The error message is: 

    Error in (function (classes, fdef, mtable)  : 
    unable to find an inherited method for function ‘confront’ for signature ‘"my_data.frame", "validator", "missing"’

**Comment by markvanderloo** [comment]
this came up before. Please see the discussion [here](https://github.com/data-cleaning/validate/issues/55)
