### ISSUE TITLE
Object copying doesn't work for validator objects

### ISSUE THREAD

**Issue by AnnePetersen1** [data-cleaning/validate#83]
I read in your "introduction" vignette that one can make copies of validator objects in the following way, but I get an error:

``` 
> v1 <- validator(sex == "Male")
> v2 <- v1[]  
Error in v1[] : argument "i" is missing, with no default
``` 
I'm not sure if it works for the `validation` objects returned by `confront()`, but I don't get an error here:

```
> data(cars)
> c1 <- confront(cars, validator(speed > 0))
> c2 <- c1[]
```

In any case, I would suggest also supplying a `copy()` method to follow the style of the `data.table` package.

**Comment by markvanderloo** [comment]
Thats a bug, since according to our manual and specification it should work. A workaround until it gets fixed is this:

```r
v <- validator(sex == "male")
w <- v[TRUE]
```

**Comment by AnnePetersen1** [comment]
Thanks, that works.
