### ISSUE TITLE
Improve documentation concerning possible validation rules

### ISSUE THREAD

**Issue by matthiasgomolka** [data-cleaning/validate#85]
Hi, while skimming through the [`errorlocate` reference manual](https://cran.r-project.org/web/packages/errorlocate/errorlocate.pdf), I stumbled over `is_conditional()`. Therefore, I tried to use conditional validation rules in `validate` and it worked like a charm. Unfortunately, I could not find any hints on this in the `validate` documentation.

Thus, it would be great if there was a list with common examples of what's possible to put into a validation rule. This could be placed in another vignette.

I think I read somewhere that everything is allowed which evaluates to `logical` (could not find this right now), but being more explicit would foster the work with `validate`.

PS: Thanks for this great package. I just started to write a package for the exact same purpose at Deutsche Bundesbank when I found yours which perfectly fits my needs.

**Comment by markvanderloo** [comment]
Hi,
Thanks for your efforts!

You make a valid point. The background is rather practical: we have focused our writing efforts on the [book](https://www.amazon.com/Statistical-Data-Cleaning-Applications-R/dp/1118897153) we publised earlier this year.

`validate` has been quite thoroughly tested, and you can find example rules and implementations also in [this github repo](https://github.com/data-cleaning/ValidatPoC). It has a good README so should be pretty self-explanatory.

Regarding the `validate` DSL. We are writing a paper on that (and you find information in the book as well). A summary of the syntax can be found by loading `validate` and the typing `?syntax` in the R command line.

**Comment by markvanderloo** [comment]
I'll close this, as I think that the [cookbook](https://data-cleaning.github.io/validate/) covers it.
