### ISSUE TITLE
Using If statements when writing rules

### ISSUE THREAD

**Issue by AdamOlsonMN** [data-cleaning/validate#88]
Very exciting package! I have read through the documentation / vignettes and I am wondering if the functionality of making rules apply to certain rows based on conditional ifs is available. 

For instance, I have a dataset of American states, and I would like to develop rules for each state (variable name = State) so Minnesota would have 5 rules specific to Minnesota, where Wisconsin would have five different rules (potentially based on the same variables).

Thank you!

**Comment by markvanderloo** [comment]
Thanks for the compliment!


I think we have a similar issue somewhere at GH. It isdefinetely  on our minds but there are several things that make it complicated. One is how to gather and represent results when rules are executed conditionally. Basically for reasons of time we decided to leave this to the workflow external to validate. 

By the end of this year and first half of 2019 we will be able to devote more resources to validate again and this will definitely be on the list.
