### ISSUE TITLE
`print` method fails with empty validator

### ISSUE THREAD

**Issue by dpritchard** [data-cleaning/validate#93]
Perhaps related to #87 (at least as far as it relates to an empty validator)...

```r
v <- validator()
d <- data.frame()
confront(d, v)
```

results in:

```
Error in sum(sapply(object$._warn, function(w) !is.null(w))) : 
  invalid 'type' (list) of argument
```

The problem is `sapply` (for example) on [confrontation.R#L336](https://github.com/data-cleaning/validate/blob/f7030c5e287bc36f33770d8772b1eaf71f6afeb8/pkg/R/confrontation.R#L336).

Suggest moving from `sapply ` to `vapply` to enforce type?

```r
g <- list() # The case for an empty validator
h <- list(NULL, 'F', 1, NA, NaN) #  A list with some non-NULL components
sum(sapply(g,function(w)!is.null(w))) # Fails
sum(sapply(h,function(w)!is.null(w))) # 4
# vs. (assuming the output when applied to $._warn will always be a single logical ?!)
sum(vapply(g, function(w)!is.null(w), FUN.VALUE = logical(1))) # Works as expected (4)
sum(vapply(h, function(w)!is.null(w), FUN.VALUE = logical(1))) # 4
```

It seems there are quite a few cases of `sapply` which might benefit from this change?

I think that empty validators could be quite useful... At the moment you can confront with one or more rules (which I am sure is the design case). But it would be nice to be able to confront with zero or more rules and have a friendly (at least non-error) output if the validator is empty.

**Comment by markvanderloo** [comment]
Thanks for reporting. I'm traveling now but we'll get into this when I'm back.
